# Generated by Django 5.1.4 on 2025-12-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_age', models.IntegerField()),
                ('stud_gender', models.CharField(max_length=100)),
                ('stud_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
